### ISSUE TITLE
Read Django Documentation

### ISSUE THREAD

**Issue by PolinaDolgova** [ssu-411/project#9]
- https://docs.djangoproject.com/en/2.0/
- https://djbook.ru/rel1.7/
@Teyvelina @Victurus @SelinaIrra

**Comment by esikachev** [comment]
ETA: 7PM

**Comment by Victurus** [comment]
I've read tutorial partially. Understand main, basic concepts.

**Comment by PolinaDolgova** [comment]
I have read documentation and understood basic concepts and abilities.

**Comment by esikachev** [comment]
waiting for @SelinaIrra

**Comment by SelinaIrra** [comment]
Task done, i have read  basic concepts.
